site_name: Programació d'Intel·ligència Artificial - CE Big Data i IA
docs_dir: "md"
site_dir: "docs"
nav:
  # - Unitat 2: 
  #   - 1. Preparació de l'entorn: U02 Python/01_Entorns_i_projectes.md
  #   - 2. Tipus de Dades. Operadors: U02 Python/02_Tipus_Variables_Operadors.md
  #   - 3. Estructures de control: U02 Python/03_Estructures_de_control.md
  #   - 4. Funcions: U02 Python/04_Funcions.md
  #   - 5. Estructures de dades: U02 Python/05_Estructures_de_dades.md
  #   - 6. Programació orientada a objectes: U02 Python/06_POO.md
  #   - 7. Projecte: U02 Python/07_Projecte.md
  #   - 8. Prova Jupyter: U02 Python/Sorting.md
  #   - 9. Prova url: U02 Python/index.html
  - Unitat 3: 
    - 1. Introducció: U03 Python aplicat al Big Data i Intel·ligencia Artificial/0. Index.md
    - 2. Manipulació de Dades amb Numpy: U03 Python aplicat al Big Data i Intel·ligencia Artificial/1. NumPy .md
    - 3. Manipulació de Dades amb Pandas: U03 Python aplicat al Big Data i Intel·ligencia Artificial/2. Pandas.md
    - 4. Visualització de dades amb Matplotlib i Seaborn: U03 Python aplicat al Big Data i Intel·ligencia Artificial/3. Matplotlib-Seaborn.md
    - 5. Introducció al Machine Learning amb Scikit-Learn: U03 Python aplicat al Big Data i Intel·ligencia Artificial/4. Sklearn.md
    - 6. Introducció al DeepLearning amb Keras: U03 Python aplicat al Big Data i Intel·ligencia Artificial/5. Keras.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme: 
  name: material
  logo: img/jaume.png
  language: ca 
  palette:
#   - primary: purple
#    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    

    
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

# extra_css:
#   - css/extra.css


plugins:
  - search
#  - pdf-export